server:
  port: 8443
spring:
  cloud:
    gateway:
      routes:
      - id: mcloud-demo
        uri: lb://mcloud-demo
        predicates:
        - Path=/demo/**
        filters:
        - RewritePath=/demo/(?<segment>.*), /$\{segment}