spring:
  application:
    name: mcloud-demo
  messages:
    basename: i18n/messages
eureka:
  instance:
    appname: mcloud-demo
    hostname: mcloud-demo
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
---
server:
  port: 8081
spring:
  profiles: peer1
---
server:
  port: 8082
spring:
  profiles: peer2